name: Merge upstream branches
on:
  push:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '0 1 * * *'
jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: changfengoss
          base: pub
          head: pub
